server:
  port: ${SERVER_PORT}

eureka:
  instance:
    # DESC: Setting 'true' tells this service to register with eureka using its IP address instead of its hostname as obtained by the OS/DNS
    # RECOMMENDED: Setting 'true' to 'prefer-ip-address' is the recommended approach.
    prefer-ip-address: false
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
    statusPageUrl: http://${EUREKA_INSTANCE_HOSTNAME}:${SERVER_PORT}/info
    healthCheckUrl: http://${EUREKA_INSTANCE_HOSTNAME}:${SERVER_PORT}/info

  client:
    # NOTE: Turn these settings "off" (to false) when you run Eureka locally in standalone mode (no cluster).
    # REASON: We only have a single Eureka server and not a cluster of Eureka servers (not registering Eureka servers with each other nor fetching information from each other).
    register-with-eureka: true
    # This is a standalone Eureka server, don't try to fetch registry data from other Eureka servers
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
